// WARNING: auto-generated by Makefile release target -- run 'make release' to update

package envs

const (
	Version     = "v1.0.9"
	GitCommit   = "258761a"          // the commit JUST BEFORE the release
	VersionDate = "2023-09-01 08:16" // UTC
)
