// WARNING: auto-generated by Makefile release target -- run 'make release' to update

package envs

const (
	Version     = "v1.0.2"
	GitCommit   = "946655e" // the commit JUST BEFORE the release
	VersionDate = "2021-04-29 11:04" // UTC
)

