// WARNING: auto-generated by Makefile release target -- run 'make release' to update

package envs

const (
	Version     = "v1.0.4"
	GitCommit   = "999b931"          // the commit JUST BEFORE the release
	VersionDate = "2023-03-14 01:52" // UTC
)
