// Copyright (c) 2023, The Emergent Authors. All rights reserved.
// Use of this source code is governed by a BSD-style
// license that can be found in the LICENSE file.

package cond

var AllConditions = map[string]Condition{
	"USDebug": {
		Name:          "USDebug",
		Desc:          "For debugging, 100% reward, CS A",
		Block:         "USDebug",
		FixedProb:     true,
		NIters:        51,
		BlocksPerIter: 8,
		Permute:       true,
		LoadWeights:   false,
		WeightsFile:   "",
		LoadStBlk:     0,
	},
	"PosAcq_B50": {
		Name:          "PosAcq_B50",
		Desc:          "Pavlovian conditioning w/ positively-valenced US: A_R_POS, B at 50%",
		Block:         "PosAcq_B50",
		FixedProb:     true,
		NIters:        51,
		BlocksPerIter: 8,
		Permute:       true,
		LoadWeights:   false,
		WeightsFile:   "",
		LoadStBlk:     0,
	},
	"PosAcq_A50": {
		Name:          "PosAcq_A50",
		Desc:          "Pavlovian conditioning w/ positively-valenced US: A_R_POS at 50%",
		Block:         "PosAcq_A50",
		FixedProb:     true,
		NIters:        51,
		BlocksPerIter: 10,
		Permute:       true,
		LoadWeights:   false,
		WeightsFile:   "",
		LoadStBlk:     0,
	},
	"US0": {
		Name:          "US0",
		Desc:          "No US at all",
		Block:         "US0",
		FixedProb:     true,
		NIters:        5,
		BlocksPerIter: 100,
		Permute:       true,
		LoadWeights:   false,
		WeightsFile:   "",
		LoadStBlk:     0,
	},
	"PosAcqPreSecondOrder": {
		Name:          "PosAcqPreSecondOrder",
		Desc:          "Pavlovian conditioning w/ positively-valenced US: A_R_POS, B at 50%",
		Block:         "PosAcqPreSecondOrder",
		FixedProb:     true,
		NIters:        51,
		BlocksPerIter: 8,
		Permute:       true,
		LoadWeights:   false,
		WeightsFile:   "",
		LoadStBlk:     0,
	},
	"PosAcq_B50Cont": {
		Name:          "PosAcq_B50Cont",
		Desc:          "Pavlovian conditioning w/ positively-valenced US: A_R_POS, B at 50% reinf, continue using prior weights",
		Block:         "PosReacq",
		FixedProb:     true,
		NIters:        50,
		BlocksPerIter: 8,
		Permute:       true,
		LoadWeights:   false,
		WeightsFile:   "wts/PVLVNet_AB_POS_trn.00_0050.wts.gz",
		LoadStBlk:     0,
	},
	"PosAcq_B100": {
		Name:          "PosAcq_B100",
		Desc:          "Pavlovian conditioning w/ positively-valenced US: A_R_POS, B at 100%",
		Block:         "PosAcq_B100",
		FixedProb:     true,
		NIters:        50,
		BlocksPerIter: 8,
		Permute:       true,
		LoadWeights:   false,
		WeightsFile:   "",
		LoadStBlk:     0,
	},
	"PosAcq_B100Cont": {
		Name:          "PosAcq_B100Cont",
		Desc:          "Pavlovian conditioning w/ positively-valenced US: A_R_POS -- continue w/ wts",
		Block:         "PosAcq_B100",
		FixedProb:     true,
		NIters:        50,
		BlocksPerIter: 8,
		Permute:       true,
		LoadWeights:   false,
		WeightsFile:   "wts/PVLVNet_AB_POS_trn.00_0050.wts.gz",
		LoadStBlk:     0,
	},
	"PosAcqEarlyUS_test": {
		Name:          "PosAcqEarlyUS_test",
		Desc:          "Testing session: after pos_acq trng, deliver US early or late",
		Block:         "PosAcqEarlyUS_test",
		FixedProb:     true,
		NIters:        5,
		BlocksPerIter: 2,
		Permute:       false,
		LoadWeights:   false,
		WeightsFile:   "wts/PVLVNet_AB_POS_trn.00_0050.wts.gz",
		LoadStBlk:     0,
	},
	"PosAcq_B25": {
		Name:          "PosAcq_B25",
		Desc:          "Pavlovian conditioning w/ positively-valenced US: A_R_POS",
		Block:         "PosAcq_B25",
		FixedProb:     true,
		NIters:        200,
		BlocksPerIter: 8,
		Permute:       true,
		LoadWeights:   false,
		WeightsFile:   "",
		LoadStBlk:     0,
	},
	"PosExtinct": {
		Name:          "PosExtinct",
		Desc:          "Pavlovian extinction: A_NR_POS",
		Block:         "PosExtinct",
		FixedProb:     false,
		NIters:        50,
		BlocksPerIter: 8,
		Permute:       true,
		LoadWeights:   false,
		WeightsFile:   "wts/PVLVNet_AB_POS_trn.00_0050.wts.gz",
		LoadStBlk:     0,
	},
	"PosCondInhib": {
		Name:          "PosCondInhib",
		Desc:          "conditioned inhibition training: AX_NR_POS, A_R_POS interleaved",
		Block:         "PosCondInhib",
		FixedProb:     false,
		NIters:        25,
		BlocksPerIter: 8,
		Permute:       true,
		LoadWeights:   false,
		WeightsFile:   "wts/PVLVNet_AB_POS_trn.00_0050.wts.gz",
		LoadStBlk:     0,
	},
	"PosSecondOrderCond": {
		Name:          "PosSecondOrderCond",
		Desc:          "second order conditioning training: AB_NR_POS, A_R_POS interleaved; A = 1st order, F = 2nd order CS",
		Block:         "PosSecondOrderCond",
		FixedProb:     false,
		NIters:        10,
		BlocksPerIter: 50,
		Permute:       true,
		LoadWeights:   false,
		WeightsFile:   "wts/PVLVNet_AB_POS_trn.00_0050.wts.gz",
		LoadStBlk:     0,
	},
	"PosCondInhib_test": {
		Name:          "PosCondInhib_test",
		Desc:          "Testing session: A_NR_POS, AX_NR_POS, and X_NR_POS cases",
		Block:         "PosCondInhib_test",
		FixedProb:     false,
		NIters:        5,
		BlocksPerIter: 6,
		Permute:       false,
		LoadWeights:   false,
		WeightsFile:   "wts/PVLVNet_AB_POS_cond_inhib_trn.00_0050.wts.gz",
		LoadStBlk:     0,
	},
	"NegAcq": {
		Name:          "NegAcq",
		Desc:          "Pavlovian conditioning w/ negatively-valenced US: D_R_NEG",
		Block:         "NegAcq",
		FixedProb:     false,
		NIters:        76,
		BlocksPerIter: 10,
		Permute:       true,
		LoadWeights:   false,
		WeightsFile:   "",
		LoadStBlk:     0,
	},
	"NegAcqFixedProb": {
		Name:          "NegAcqFixedProb",
		Desc:          "Pavlovian conditioning w/ negatively-valenced US: A_R_NEG",
		Block:         "NegAcq",
		FixedProb:     true,
		NIters:        150,
		BlocksPerIter: 8,
		Permute:       false,
		LoadWeights:   false,
		WeightsFile:   "",
		LoadStBlk:     0,
	},
	"PosAcqOmit": {
		Name:          "PosAcqOmit",
		Desc:          "Pavlovian conditioning w/ positively-valenced US: A_R_POS, A_NR_POS trials, interleaved",
		Block:         "PosAcqOmit",
		FixedProb:     false,
		NIters:        10,
		BlocksPerIter: 8,
		Permute:       true,
		LoadWeights:   false,
		WeightsFile:   "",
		LoadStBlk:     0,
	},
	"NegCondInh": {
		Name:          "NegCondInh",
		Desc:          "condition inhibition w/ negatively-valenced US: CZ_NR_NEG, C_R_NEG interleaved; i.e.,  Z = security signal",
		Block:         "NegCondInhib",
		FixedProb:     false,
		NIters:        75,
		BlocksPerIter: 10,
		Permute:       true,
		LoadWeights:   false,
		WeightsFile:   "wts/PVLVNet_DE_NEG_trn.00_0150.wts.gz",
		LoadStBlk:     0,
	},
	"NegCondInh_test": {
		Name:          "NegCondInh_test",
		Desc:          "condition inhibition w/ negatively-valenced US: CZ_NR_NEG, C_R_NEG interleaved; i.e.,  Z = security signal",
		Block:         "NegCondInhib_test",
		FixedProb:     false,
		NIters:        5,
		BlocksPerIter: 6,
		Permute:       false,
		LoadWeights:   false,
		WeightsFile:   "wts/PVLVNet_DU_NEG_trn.00_0150.wts.gz",
		LoadStBlk:     0,
	},
	"NegExtinct": {
		Name:          "NegExtinct",
		Desc:          "Pavlovian conditioning w/ negatively-valenced US: A_R_NEG",
		Block:         "NegExtinct",
		FixedProb:     false,
		NIters:        75,
		BlocksPerIter: 8,
		Permute:       true,
		LoadWeights:   false,
		WeightsFile:   "wts/PVLVNet_DE_NEG_trn.00_0150.wts.gz",
		LoadStBlk:     0,
	},
	"PosAcq_cxA": {
		Name:          "PosAcq_cxA",
		Desc:          "Pavlovian conditioning w/ positively-valenced US: A_R_POS, A_R_POS_omit trials, interleaved",
		Block:         "PosAcq_cxA",
		FixedProb:     false,
		NIters:        26,
		BlocksPerIter: 10,
		Permute:       false,
		LoadWeights:   false,
		WeightsFile:   "",
		LoadStBlk:     0,
	},
	"PosExtinct_cxB": {
		Name:          "PosExtinct_cxB",
		Desc:          "Pavlovian conditioning w/ positively-valenced US: A_R_POS, A_R_POS_omit trials, interleaved",
		Block:         "PosExtinct_cxB",
		FixedProb:     false,
		NIters:        25,
		BlocksPerIter: 10,
		Permute:       false,
		LoadWeights:   false,
		WeightsFile:   "wts/PVLVNet_A_cxA_vs.wts.gz",
		LoadStBlk:     0,
	},
	"PosRenewal_cxA": {
		Name:          "PosRenewal_cxA",
		Desc:          "Pavlovian conditioning w/ positively-valenced US: A_R_POS, A_R_POS_omit trials, interleaved",
		Block:         "PosRenewal_cxA",
		FixedProb:     false,
		NIters:        1,
		BlocksPerIter: 2,
		Permute:       false,
		LoadWeights:   false,
		WeightsFile:   "wts/PVLVNet_A_cxB_vs.wts.gz",
		LoadStBlk:     0,
	},
	"PosBlocking_A_train": {
		Name:          "PosBlocking_A_train",
		Desc:          "Blocking experiment",
		Block:         "PosBlocking_A_train",
		FixedProb:     false,
		NIters:        50,
		BlocksPerIter: 1,
		Permute:       false,
		LoadWeights:   false,
		WeightsFile:   "",
		LoadStBlk:     0,
	},
	"PosBlocking": {
		Name:          "PosBlocking",
		Desc:          "Blocking experiment",
		Block:         "PosBlocking",
		FixedProb:     false,
		NIters:        50,
		BlocksPerIter: 2,
		Permute:       false,
		LoadWeights:   false,
		WeightsFile:   "wts/PVLVNet_posblocking_A_train_300.wts.gz",
		LoadStBlk:     0,
	},
	"PosBlocking_test": {
		Name:          "PosBlocking_test",
		Desc:          "Blocking experiment",
		Block:         "PosBlocking_test",
		FixedProb:     false,
		NIters:        25,
		BlocksPerIter: 1,
		Permute:       false,
		WeightsFile:   "wts/PVLVNet_posblocking_A_AB_200.wts.gz",
		LoadStBlk:     0,
	},
	"PosBlocking2_test": {
		Name:          "PosBlocking2_test",
		Desc:          "Blocking experiment",
		Block:         "PosBlocking2_test",
		FixedProb:     false,
		NIters:        25,
		BlocksPerIter: 2,
		Permute:       false,
		LoadWeights:   false,
		WeightsFile:   "wts/PVLVNet_posblocking_A_AB_200.wts.gz",
		LoadStBlk:     0,
	},
	"NegBlocking_E_train": {
		Name:          "NegBlocking_E_train",
		Desc:          "Blocking experiment",
		Block:         "NegBlocking_E_train",
		FixedProb:     false,
		NIters:        300,
		BlocksPerIter: 1,
		Permute:       false,
		LoadWeights:   false,
		WeightsFile:   "",
		LoadStBlk:     0,
	},
	"NegBlocking": {
		Name:          "NegBlocking",
		Desc:          "Blocking experiment",
		Block:         "NegBlocking",
		FixedProb:     false,
		NIters:        200,
		BlocksPerIter: 2,
		Permute:       false,
		LoadWeights:   false,
		WeightsFile:   "wts/PVLVNet_negblocking_E_train.wts.gz",
		LoadStBlk:     0,
	},
	"NegBlocking_test": {
		Name:          "NegBlocking_test",
		Desc:          "Blocking experiment",
		Block:         "NegBlocking_test",
		FixedProb:     false,
		NIters:        25,
		BlocksPerIter: 1,
		Permute:       false,
		LoadWeights:   false,
		WeightsFile:   "wts/PVLVNet_negblocking_E_DE.wts.gz",
		LoadStBlk:     0,
	},
	"PosAcqMag": {
		Name:          "PosAcqMag",
		Desc:          "Magnitude experiment",
		Block:         "PosAcqMagnitude",
		FixedProb:     false,
		NIters:        50,
		BlocksPerIter: 8,
		Permute:       false,
		LoadWeights:   false,
		WeightsFile:   "",
		LoadStBlk:     0,
	},
	"PosSumAcq": {
		Name:          "PosSumAcq",
		Desc:          "Conditioned Inhibition - A+, C+",
		Block:         "PosSumAcq",
		FixedProb:     false,
		NIters:        450,
		BlocksPerIter: 3,
		Permute:       false,
		LoadWeights:   false,
		WeightsFile:   "",
		LoadStBlk:     0,
	},
	"PosSumCondInhib": {
		Name:          "PosSumCondInhib",
		Desc:          "Conditioned Inhibition - AX-, A+",
		Block:         "PosCondInhib_BY",
		FixedProb:     false,
		NIters:        300,
		BlocksPerIter: 3,
		Permute:       false,
		LoadWeights:   false,
		WeightsFile:   "wts/PVLVNet_AC_POS_trn.00_0450.wts.gz",
		LoadStBlk:     0,
	},
	"PosSum_test": {
		Name:          "PosSum_test",
		Desc:          "Conditioned Inhibition Summation Test",
		Block:         "PosSumCondInhib_test",
		FixedProb:     false,
		NIters:        5,
		BlocksPerIter: 6,
		Permute:       false,
		LoadWeights:   false,
		WeightsFile:   "wts/PVLVNet_sum_AX_POS_trn.00_0300.wts.gz",
		LoadStBlk:     0,
	},
	"NegSumAcq": {
		Name:          "NegSumAcq",
		Desc:          "Conditioned Inhibition - D-, E-",
		Block:         "NegSumAcq",
		FixedProb:     false,
		NIters:        50,
		BlocksPerIter: 3,
		Permute:       false,
		LoadWeights:   false,
		WeightsFile:   "",
		LoadStBlk:     0,
	},
	"NegSumCondInhib": {
		Name:          "NegSumCondInhib",
		Desc:          "Conditioned Inhibition - DU, D-",
		Block:         "NegCondInhib_FV",
		FixedProb:     false,
		NIters:        100,
		BlocksPerIter: 3,
		Permute:       false,
		LoadWeights:   false,
		WeightsFile:   "wts/PVLVNet_DEF_NEG_trn.00_0050.wts.gz",
		LoadStBlk:     0,
	},
	"NegSum_test": {
		Name:          "NegSum_test",
		Desc:          "Conditioned Inhibition Summation Test",
		Block:         "NegSumCondInhib_test",
		FixedProb:     false,
		NIters:        5,
		BlocksPerIter: 6,
		Permute:       false,
		LoadWeights:   false,
		WeightsFile:   "wts/PVLVNet_sum_DU_NEG_trn.00_0050.wts.gz",
		LoadStBlk:     0,
	},
	"Unblocking_train": {
		Name:          "Unblocking_train",
		Desc:          "A+++,B+++,C+",
		Block:         "Unblocking_train",
		FixedProb:     false,
		NIters:        50,
		BlocksPerIter: 2,
		Permute:       false,
		LoadWeights:   false,
		WeightsFile:   "",
		LoadStBlk:     0,
	},
	"UnblockingValue": {
		Name:          "UnblockingValue",
		Desc:          "AX+++,CZ+++",
		Block:         "UnblockingValue",
		FixedProb:     false,
		NIters:        25,
		BlocksPerIter: 1,
		Permute:       false,
		LoadWeights:   false,
		WeightsFile:   "wts/PVLVNet_ABC_POS_trn.00_0050.wts.gz",
		LoadStBlk:     0,
	},
	"UnblockingValue_test": {
		Name:          "UnblockingValue_test",
		Desc:          "A,X,C,Z",
		Block:         "UnblockingValue_test",
		FixedProb:     false,
		NIters:        5,
		BlocksPerIter: 1,
		Permute:       false,
		LoadWeights:   false,
		WeightsFile:   "wts/PVLVNet_AX_CZ_trn.00_0050.wts.gz",
		LoadStBlk:     0,
	},
	"Unblocking_trainUS": {
		Name:          "Unblocking_trainUS",
		Desc:          "A+++ (water) ,B+++ (food)",
		Block:         "Unblocking_trainUS",
		FixedProb:     false,
		NIters:        50,
		BlocksPerIter: 15,
		Permute:       false,
		LoadWeights:   false,
		WeightsFile:   "",
		LoadStBlk:     0,
	},
	"UnblockingIdentity": {
		Name:          "UnblockingIdentity",
		Desc:          "AX+++(water),BY+++(water)",
		Block:         "UnblockingIdentity",
		FixedProb:     false,
		NIters:        25,
		BlocksPerIter: 20,
		Permute:       false,
		LoadWeights:   false,
		WeightsFile:   "wts/PVLVNet_ABC_POS_US_trn.00_0050.wts.gz",
		LoadStBlk:     0,
	},
	"UnblockingIdentity_test": {
		Name:          "UnblockingIdentity_test",
		Desc:          "A,X,B,Y",
		Block:         "UnblockingIdentity_test",
		FixedProb:     false,
		NIters:        5,
		BlocksPerIter: 4,
		Permute:       false,
		LoadWeights:   false,
		WeightsFile:   "wts/PVLVNet_AX_BY_trn.00_0050.wts.gz",
		LoadStBlk:     0,
	},
	"PosAcqMagChange": {
		Name:          "PosAcqMagChange",
		Desc:          "Magnitude experiment",
		Block:         "PosAcqMagnitudeChange",
		FixedProb:     false,
		NIters:        50,
		BlocksPerIter: 4,
		Permute:       false,
		LoadWeights:   false,
		WeightsFile:   "wts/PVLVNet_AB_POS_MAG_trn.00_0050.wts.gz",
		LoadStBlk:     0,
	},
	"NegAcqMag": {
		Name:          "NegAcqMag",
		Desc:          "Magnitude experiment",
		Block:         "NegAcqMagnitude",
		FixedProb:     false,
		NIters:        51,
		BlocksPerIter: 8,
		Permute:       false,
		LoadWeights:   false,
		WeightsFile:   "",
		LoadStBlk:     0,
	},
	"NegAcqMagChange": {
		Name:          "NegAcqMagChange",
		Desc:          "Magnitude experiment",
		Block:         "NegAcqMagnitudeChange",
		FixedProb:     false,
		NIters:        50,
		BlocksPerIter: 4,
		Permute:       false,
		LoadWeights:   false,
		WeightsFile:   "",
		LoadStBlk:     0,
	},
	"Overexpect_train": {
		Name:          "Overexpect_train",
		Desc:          "Overexpectation training (A+, B+, C+, X+, Y-)",
		Block:         "Overexpectation_train",
		FixedProb:     false,
		NIters:        150,
		BlocksPerIter: 5,
		Permute:       false,
		LoadWeights:   false,
		WeightsFile:   "",
		LoadStBlk:     0,
	},
	"OverexpectCompound": {
		Name:          "OverexpectCompound",
		Desc:          "Overexpectation compound training (AX+, BY-, CX+, X+, Y-)",
		Block:         "OverexpectationCompound",
		FixedProb:     false,
		NIters:        150,
		BlocksPerIter: 5,
		Permute:       false,
		LoadWeights:   false,
		WeightsFile:   "wts/PVLVNet_ABCXY_trn.00_0150.wts.gz",
		LoadStBlk:     0,
	},
	"Overexpect_test": {
		Name:          "Overexpect_test",
		Desc:          "Overexpectation test ( A-, B-, C-, X-)",
		Block:         "Overexpectation_test",
		FixedProb:     false,
		NIters:        5,
		BlocksPerIter: 5,
		Permute:       false,
		LoadWeights:   false,
		WeightsFile:   "wts/PVLVNet_AXBYCY_trn.00_0150.wts.gz",
		LoadStBlk:     0,
	},
	"PosNeg": {
		Name:          "PosNeg",
		Desc:          "Positive negative test - W equally reinforced with reward + punishment",
		Block:         "PosNeg",
		FixedProb:     false,
		NIters:        150,
		BlocksPerIter: 6,
		Permute:       false,
		LoadWeights:   false,
		WeightsFile:   "",
		LoadStBlk:     0,
	},
	"PosOrNegAcq": {
		Name:          "PosOrNegAcq",
		Desc:          "Positive negative acquisition - with reward or punishment on interleaved trials according to user-set probabilities",
		Block:         "PosOrNegAcq",
		FixedProb:     false,
		NIters:        150,
		BlocksPerIter: 6,
		Permute:       true,
		LoadWeights:   false,
		WeightsFile:   "",
		LoadStBlk:     0,
	},
}
